// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABdKQjuxyIAUEFdGADJolGOiuUoZMiHN0',
    appId: '1:344664954657:web:5e18c76e6d1621d6679060',
    messagingSenderId: '344664954657',
    projectId: 'sourceyangu-254',
    authDomain: 'sourceyangu-254.firebaseapp.com',
    storageBucket: 'sourceyangu-254.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxFGpeFjg0UMNxQIQsKt-ZQU_utmZdJU',
    appId: '1:344664954657:android:f604b55b275eb40b679060',
    messagingSenderId: '344664954657',
    projectId: 'sourceyangu-254',
    storageBucket: 'sourceyangu-254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZAFyrfCdE8Xvc7POPXnBNGeh5LxbxZY',
    appId: '1:344664954657:ios:84d1d0031058654c679060',
    messagingSenderId: '344664954657',
    projectId: 'sourceyangu-254',
    storageBucket: 'sourceyangu-254.firebasestorage.app',
    iosBundleId: 'com.example.sourceyangu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZAFyrfCdE8Xvc7POPXnBNGeh5LxbxZY',
    appId: '1:344664954657:ios:84d1d0031058654c679060',
    messagingSenderId: '344664954657',
    projectId: 'sourceyangu-254',
    storageBucket: 'sourceyangu-254.firebasestorage.app',
    iosBundleId: 'com.example.sourceyangu',
  );

}